import React from 'react'
import { Container, Row, Col } from "react-bootstrap";

const About = () => {
  return (
    <>
    <Container style={{marginTop : '50px'}}>
        <h1>Qui sommes-nous ?</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis recusandae expedita deserunt non porro fugit fuga ut sunt nostrum? Ipsum nostrum atque facere quis ratione iste qui tenetur cumque mollitia asperiores blanditiis delectus autem est quisquam illum, nihil ipsam eveniet necessitatibus voluptate consectetur, obcaecati saepe ad, velit quidem. Quos, recusandae cumque perspiciatis officiis in illo! Repellendus dolore nemo aperiam aut quasi saepe sed. Voluptatibus laborum blanditiis neque ipsa, officia aut, debitis provident, accusamus consequuntur mollitia repellendus nam odio facere autem sequi deserunt reiciendis nemo nobis maxime et quam non. Eveniet id officia consequuntur, ipsum dicta incidunt cum nemo maxime, modi blanditiis accusamus, inventore alias voluptates accusantium vitae consequatur illo possimus ex eaque porro perspiciatis esse! Veniam, fugit? Cumque accusantium voluptatum, consequatur inventore excepturi accusamus deserunt dolorem, asperiores aut earum ipsum facilis recusandae in quasi laudantium rerum iste fugiat, iure suscipit saepe placeat. Accusantium ratione doloremque facere sapiente accusamus harum a ducimus enim dolorem ad veniam atque illum amet nisi voluptatem inventore totam debitis, nesciunt esse beatae repellat eligendi iure? Deleniti illum rem optio corrupti, animi sit dignissimos temporibus explicabo reiciendis necessitatibus ullam numquam assumenda aperiam unde totam! Quisquam, pariatur repellendus, doloremque sed molestiae fuga nesciunt nihil expedita, sunt obcaecati doloribus!</p>
        <h1>Notre spécialité</h1>
        <Row>
            <Col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, doloremque molestias incidunt sint exercitationem repellat eius obcaecati perspiciatis odit doloribus at necessitatibus natus fuga in maxime facilis quis, et magnam neque harum veritatis. Iure porro nesciunt sunt asperiores rem nostrum provident a ipsam cumque dignissimos quas, architecto consequuntur amet consectetur doloribus quasi, voluptas nemo tempora. Earum, hic laborum! Unde, dolor eligendi alias sequi, aliquam quas adipisci aut error neque deleniti laborum assumenda rerum recusandae fugit corrupti provident cupiditate nihil tempore obcaecati. Hic dolores provident quo iste. Veritatis possimus, numquam consectetur esse quas facilis cupiditate quasi minima deleniti iusto culpa architecto similique doloribus ab officia necessitatibus, autem commodi facere sit ipsa! Facere animi possimus nisi tempore accusamus suscipit officia architecto, nulla excepturi aliquam voluptas ab? Molestiae temporibus sit, natus quos explicabo aut unde quis consequuntur dignissimos, ut nemo enim id nam necessitatibus suscipit commodi tempora obcaecati provident modi, eius doloremque nobis corporis repellendus dolorem. Perspiciatis iusto consequatur eius distinctio tenetur eligendi nihil deleniti blanditiis, dolor odit dignissimos recusandae accusantium repellat est? Sapiente fugit corporis corrupti voluptatibus sunt quisquam in veniam, quibusdam iure necessitatibus eius minima voluptas amet quas inventore neque perferendis dicta iusto alias blanditiis explicabo quidem similique? Aspernatur, aperiam ratione!</p>
            </Col>
            <Col md={6}>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sit reprehenderit, nobis laudantium corrupti veniam voluptatibus fugit ducimus? Ipsa ut unde officia velit culpa dolorum, assumenda voluptatum vitae saepe inventore. Consequatur alias aliquid minima officiis pariatur earum voluptate natus omnis, enim optio quisquam nisi incidunt provident! In voluptatibus, sequi dolorem ipsam neque fuga sed sint eum velit. Expedita aliquid reprehenderit ut cupiditate, eligendi eveniet quaerat labore, sint quod assumenda, nihil in! Quaerat ullam dolores ducimus dolorum. Necessitatibus placeat distinctio consequuntur sequi cumque dolorem recusandae enim architecto nisi nesciunt laudantium exercitationem impedit, doloribus deleniti expedita iure provident, optio ipsa earum dignissimos nihil magnam quibusdam aliquid. Ipsum, in iste ducimus unde excepturi reprehenderit voluptatum temporibus sapiente dolorum recusandae perspiciatis. Quis illo, autem ipsum sapiente corporis porro aut suscipit tenetur harum, unde, voluptate mollitia sit eum consequuntur alias animi soluta laudantium voluptatem vitae ratione repudiandae doloremque qui deleniti? Similique ea cupiditate illo molestiae repellendus! Doloribus quia similique perspiciatis unde nesciunt, dolore laudantium asperiores impedit eveniet, excepturi qui cum quos quas culpa voluptate dicta, rerum saepe id sint? Beatae necessitatibus aperiam amet officia sapiente vero veniam debitis! Cum doloremque sit velit, tempore nihil, magni accusantium voluptates odit quae ipsa consequatur rerum eveniet alias inventore saepe.</p>
            </Col>
        </Row>
        <Row>
            <h1>Le Chef</h1>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique nam inventore vel assumenda, aspernatur sunt quod esse possimus, quisquam laborum deleniti. Doloremque maxime debitis eum minus exercitationem. Culpa unde reiciendis delectus, debitis similique quos consequatur maxime quae amet excepturi dolore molestias. Dolorum, sint! Tempore aliquam eos quibusdam veritatis atque! Enim inventore dignissimos ab dolorem, consectetur eveniet consequuntur labore dicta. Sed suscipit nobis adipisci. Dolor ratione quas eum sequi perspiciatis, adipisci, consequuntur esse quisquam deleniti nobis recusandae exercitationem excepturi. Voluptate esse ratione perspiciatis explicabo possimus neque soluta quas consequatur, cupiditate eaque odit sequi assumenda id provident enim eos veritatis tenetur deserunt.</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit officiis sed veniam culpa autem accusantium doloribus accusamus omnis ex aperiam, maxime quibusdam quaerat nihil! Modi aperiam ullam blanditiis cupiditate tempore consequuntur a rerum error nulla quo, ratione quaerat, suscipit ab nam consectetur tempora eos fugit quod libero repellat minima soluta alias nesciunt! Sed voluptatem dolor eaque quod quis, excepturi nesciunt veniam asperiores iusto, sunt a fugiat ab ipsa repudiandae! Illo porro facilis nemo nulla qui natus laborum officiis non veniam minima! Fuga, exercitationem reiciendis quam in, deleniti error magni perferendis porro officia corrupti iste quas eaque ex, sequi doloribus beatae.</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quos quisquam sapiente! Doloribus modi fugiat ratione. Nulla facilis quae modi similique magnam minus. Repellat qui beatae quaerat quas, porro cumque sed architecto sequi ratione fugit consequuntur quis dignissimos inventore velit molestias tempore at sit natus iure rem corrupti? Dolor at labore, ducimus itaque voluptate praesentium ea architecto suscipit molestias dolore, unde modi quasi natus. Consectetur, sed maiores consequuntur debitis cupiditate dicta reiciendis fugit aspernatur, magnam laborum perferendis, assumenda provident. Sit aliquid autem perferendis neque voluptatem aspernatur molestiae alias corporis tempora reiciendis. Molestiae mollitia, quo sunt esse aspernatur inventore voluptate at.</p>
            </Col>
            <Col md={3}>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat molestias nihil cumque reiciendis hic eligendi quibusdam reprehenderit deleniti illo! Amet saepe, incidunt sequi quo reprehenderit exercitationem mollitia officia rerum, illum tempora eum iure fugiat cupiditate ratione. Beatae rerum totam possimus officiis unde inventore accusamus eos necessitatibus atque, voluptatem recusandae velit quia voluptatibus quibusdam voluptates voluptate quos, dolorem sapiente! Cum ullam ipsa dolores unde adipisci similique. Maxime pariatur provident minus cum, laborum libero, ipsam officiis eaque recusandae illo consequuntur, at rem blanditiis magni facilis modi quaerat! Maxime, veniam! Quasi molestiae earum, reprehenderit nesciunt molestias doloribus eaque minus possimus vitae, modi nulla.</p>
            </Col>
        </Row>
    </Container>
    </>
  )
}

export default About